### ISSUE TITLE
Put the source code in a folder so it is easier to symlink in your Vault

### ISSUE THREAD

**Issue by madx** [lukemt/obsidian-feeds#2]
The current process requires copying the `view.js` in your Obsidian Vault, optionally (and preferably) renaming it.

I think we should have everything inside a `view` folder that we can easily symlink or copy as a whole.

This also makes it easier to add a custom `.css` file for styling (which we will require soon 😉)

**Comment by lukemt** [comment]
i just put the repo inside of my vault lol
