### ISSUE TITLE
Write a README

### ISSUE THREAD

**Issue by madx** [lukemt/obsidian-feeds#4]
The current documentation of `obsidian-feeds` is the [pinned post on Discord](https://discord.com/channels/686053708261228577/1160969028739793017/1161610835483963402).

We should have a proper and up-to-date documentation in the README file of this repository.

**Comment by madx** [comment]
As a reference, here are the contents of the pinned post as of 2023-10-17:

---

**What it is**
- This is an extended version of my "feed"-query
- See explanation and *Video* here: https://discord.com/channels/686053708261228577/710585052769157141/1157068231652155432

**How to install**
- create a folder named "feed" anywhere in your vault
- download [view.js](https://raw.githubusercontent.com/lukemt/obsidian-feeds/main/view.js) by opening the link and pressing strg+s (cmd+s on mac)
- put it in the feed folder
- and call the query in any note like so:
```
~~~dataviewjs
await dv.view("feed")
~~~
```

**Comment by lukemt** [comment]
and then we can make an announcement :D

**Comment by madx** [comment]
Maybe we should create a milestone to list all that we want to be available for the announcement?

**Comment by madx** [comment]
I updated the README as part of the preparation process for submission to the Community plugins list. I'll close this issue as I don't think it is relevant anymore
